apiVersion: apps/v1
kind: Deployment
metadata:
  name: ola
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      ola: api-app
  template:
    metadata:
      labels:
        ola: api-app
    spec:
      containers:
      - name: ola-api
        image: im3iodev/ola-api-poc:1.1
        ports:
          - containerPort: 9001
        env:
            - name: OA_API_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ola-db-secret
                  key: hostdb
            - name: OA_API_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ola-db-secret
                  key: dbname
            - name: OA_API_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ola-db-secret
                  key: password
            - name: OA_API_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ola-db-secret
                  key: port
            - name: OA_API_DB_USER
              valueFrom:
                secretKeyRef:
                  name: ola-db-secret
                  key: username
            - name: OA_API_LOG_LEVEL
              value: debug
            - name: OA_API_LOG_SQL
              value: "true"
            - name: OA_API_ORDER_DEV_PREFIX
              value: "15"
            - name: OA_API_POSTPAID_DEV_PREFIX
              value: "TESTMYIMTRI-"
            - name: OA_API_POSTPAID_UPLOAD_MAX
              value: 2M
            - name: OA_API_SCHEDULER
              value: "false"
            - name: OA_API_NGSSP_BASEURL
              value: "https://esb-test.indosatooredoo.com:8084/GenericReqHandler/ProvServiceAsync"
        resources:
            requests:
                cpu: "250m"
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    ola: api-app
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
